### ISSUE TITLE
Wieder zum laufen bringen

### ISSUE THREAD

**Issue by MBrill** [VRLAB-HSKL/TowerOfHanoi#1]
Wir müssen das Projekt neu zum laufen bringen. 

1. Wir beginnen mit der jetzt im repo liegenden Version von Florian Oswald.
2. Dann bringen wir die Weiterentwicklung von Thomas Schentarra auch zu laufen.

**Comment by gizzmo88** [comment]
Die Fehlermeldungen stammten von SteamVR. Habe das Plugin auf den neusten stand gebracht. SteamVR hat auf das neue InputSystem umgestellt, was bedeutet die Input-Steuerung muss neu bzw. umgeschrieben werden.
